import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, resolve } from 'path';
import process from 'process';

const ROOT = resolve(new URL('../..', import.meta.url).pathname);
const CANONICAL_EVENTS = resolve(ROOT, 'packages/contracts/src/events.js');
const CANONICAL_TYPES = resolve(ROOT, 'packages/contracts/src/index.ts');
const GENERATED_BANNER = '// Generated by `npm run contracts:sync`. Do not edit by hand.\n\n';

function normalizeContent(value) {
  return value.endsWith('\n') ? value : `${value}\n`;
}

function buildClientIndex(typesSource) {
  return typesSource.replace("from './events.js';", "from './socketEvents';");
}

async function readUtf8(path) {
  return readFile(path, 'utf8');
}

async function writeIfChanged(path, content, checkOnly) {
  const normalized = normalizeContent(content);
  const expected = `${GENERATED_BANNER}${normalized}`;
  const current = await readUtf8(path).catch(() => null);

  if (current === expected) {
    console.log(`${checkOnly ? 'verified' : 'up to date'} ${path}`);
    return true;
  }

  if (checkOnly) {
    console.error(`out of sync ${path}`);
    return false;
  }

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, expected, 'utf8');
  console.log(`updated ${path}`);
  return true;
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const [eventsSource, typesSource] = await Promise.all([
    readUtf8(CANONICAL_EVENTS),
    readUtf8(CANONICAL_TYPES),
  ]);

  const targets = [
    {
      path: resolve(ROOT, 'client/src/contracts/socketEvents.ts'),
      content: eventsSource,
    },
    {
      path: resolve(ROOT, 'client/src/contracts/index.ts'),
      content: buildClientIndex(typesSource),
    },
    {
      path: resolve(ROOT, 'server/lib/contracts/socketEvents.js'),
      content: eventsSource,
    },
  ];

  const results = await Promise.all(
    targets.map((target) => writeIfChanged(target.path, target.content, checkOnly)),
  );

  if (results.every(Boolean)) return;
  process.exit(1);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
