// Generated by `npm run contracts:sync`. Do not edit by hand.

export const SocketEvents = /** @type {const} */ ({
  // Client → Server
  VAULT_SYNC_REQUEST: 'vault-sync-request',
  FILE_READ:          'file-read',
  FILE_WRITE:         'file-write',
  FILE_CREATE:        'file-create',
  FILE_DELETE:        'file-delete',
  FILE_RENAME:        'file-rename',
  FILE_CLAIM:         'file-claim',
  FILE_UNCLAIM:       'file-unclaim',
  PRESENCE_OPENED:    'presence-file-opened',
  PRESENCE_CLOSED:    'presence-file-closed',
  USER_STATUS:        'user-status-changed',
  // Server → Client
  FILE_UPDATED:       'file-updated',
  FILE_CREATED:       'file-created',
  FILE_DELETED:       'file-deleted',
  FILE_RENAMED:       'file-renamed',
  FILE_CLAIMED:       'file-claimed',
  FILE_UNCLAIMED:     'file-unclaimed',
  USER_JOINED:        'user-joined',
  USER_LEFT:          'user-left',
  EXTERNAL_UPDATE:    'external-update',
});
